# Generated by Django 5.2.7 on 2025-11-03 04:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Id_Marca', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMarca', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Id_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEmpresa', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Debe tener 8 digitos', regex='^\\d{8}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Existencia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.categoria')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.marca')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('Id_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Compra', models.DateField(default=django.utils.timezone.now)),
                ('SubTotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('Total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.proveedor')),
            ],
            options={
                'ordering': ['-Fecha_Compra', '-Id_Compra'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Id_Venta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Venta', models.DateField(default=django.utils.timezone.now)),
                ('Total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente')),
            ],
            options={
                'ordering': ['-Fecha_Venta', '-Id_Venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadVendida', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('SubTotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='ventas.producto')),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadC', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('PrecioC', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('SubTotalDC', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='ventas.compra')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='ventas.producto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Compra', 'Producto'), name='compra_producto_unico'), models.CheckConstraint(condition=models.Q(('CantidadC__gte', 1)), name='compra_det_cantidad_ge_1'), models.CheckConstraint(condition=models.Q(('PrecioC__gte', 0)), name='compra_det_precio_ge_0'), models.CheckConstraint(condition=models.Q(('SubTotalDC__gte', 0)), name='compra_det_subtotal_ge_0')],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('Existencia__gte', 0)), name='producto_existencia_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('SubTotal__gte', 0)), name='compra_subtotal_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('Total__gte', 0)), name='compra_total_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('Total__gte', 0)), name='venta_total_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.UniqueConstraint(fields=('Venta', 'Producto'), name='venta_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('CantidadVendida__gte', 1)), name='cantidad_ge_1'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('PrecioUnitario__gte', 0)), name='precio_unitario_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('SubTotal__gte', 0)), name='detalle_subtotal_ge_0'),
        ),
    ]
